# ~/.config/mise/config.toml
# https://qiita.com/uhooi/items/0fe7cedd16a09940a710
[tools]
awscli = "latest"
node = "latest"
# ruby = "3.4.2"
neovim = "latest"
terraform = "latest"
kubectl = "latest"
# go = "latest"
# postgres = "17"
python = "latest"
gcloud = "latest"
codex = "latest"
docker-cli = "latest"
colima = "latest"
lima = "latest"
claude = "latest"
uv = "latest"

[tasks.colima-stop]
run = "'colima stop'"

[tasks.colima-status]
run = "'colima status'"

[tasks.colima-start]
run = "'colima start'"
